### PR TITLE
Updated MoneyUtils.max() and MoneyUtils.min() to receive multiple val…

### PR DESCRIPTION
**Pull request by pedrocborges2**
Math max/min are flat functions, they can take any number of arguments, having MoneyUtils deal with only 2 is limiting.

### CODE REVIEW

**Comment by pedrocborges2** [comment]
Similar to org.apache.commons.lang3.ObjectUtils max and min methods.

**Comment by jodastephen** [comment]
I tried this on a branch, but needed to keep the old methods to ensure compatibility. Ultimately, I felt that it doesn't add enough value. Min/max of collections can be achieved using the `Collections` class. Min/max of arrays can be achieved using Google Guava `Ordering`. And Java 8 `Stream` gives further min/max choices. As such, this seems unnecessary (and perhaps the original min/max were unnecessary too).

**Comment by pedrocborges2** [comment]
Hi Stephen

Thanks for taking the time to review this.
I fundamentally agree with you, this doesn’t add functionality, it only adds comfort. If this was part of the Money class I wouldn’t have even went down this path, but being it in a Helper class I believe it makes sense since it allows for better code readability when getting the min/max of several JodaMoney instances.
I have two questions, 1. what about it was not 100% backwards compatible. and 2. What if the methods use one of your suggested implementations instead of cycling it on it’s own?
It’s all about helper methods to aid in code readability, not functionality per-se.

All the best
Pedro

**Comment by jodastephen** [comment]
This [page](https://wiki.eclipse.org/Evolving_Java-based_APIs_2) is a good writeup about compatibility. Removing the method would be source compatible, but not binary compatible, which is very painful for low level libraries as it creates "jar hell".

While I effectively implemented in the branch a suitable change, I decided I didn't like it enough to merge it. Its just a sense of how far it makes sense to push an OSS project. Note also that `Money` and `BigMoney` are `Comparable`, so every other comparison method will work just fine. The only advantage of these ones is null-hiding, and I'm no longer convinced that is a good idea.

**Comment by pedrocborges2** [comment]
Very well it’s your call, thanks for the link, it is quite enlightening.

All the best
Pedro

**Pull request closed without merging**
