### PR TITLE
Add support for up to 30 decimal places

### LINKED ISSUE #77: Support currencies with more than 9 decimal places in use
With the rise of cryptocurrencies, supporting currencies with greater decimal precision than 9 places would be greatly appreciated.

The current imposed limit of 9 decimal places works for many, but not all currency divisions. It breaks down when any currency based on Ethereum is used. Ethereum has a standard unit Ether which can be dividled into the Wei. Each Ether can be divided into 10^18 Wei  as its smallest denomination.

Currently I have to register multiple currency units for the Ether at various denominations in order to support the smallest denomination where I need it. This introduces potential error at every conversion in my code adding extra implementation and testing burden. In many cases, in order to avoid potential errors caused by these small divisions I just restrict my users to a max division of 9 decimal places per Ether, but this isn't ideal when tracking the currency.

I'm willing to attempt a pull request if this is something that joda money is interested in supporting.

### PR DESCRIPTION
**Pull request by coderjoe**
Fixes #77

### CODE REVIEW

**Comment by coderjoe** [comment]
It would seem that two of the test targets are no longer supported on travis. I don't want to start changing your test targets willy-nilly, so if you have alternative targets you'd prefer to use please let me know and I'll add to this PR.

Relates to: [travis-ci/travis-ci/#7964](https://github.com/travis-ci/travis-ci/issues/7964)

**Comment by jodastephen** [comment]
Can you rebase onto the latest HEAD please to fix the travis problem.

My feeling is that 99 is perhaps a little excessive in decimal places. How about 30?

**Comment by coderjoe** [comment]
Can do on both counts.

**Comment by coderjoe** [comment]
I've updated both the PR, and the issue title to reflect the update the change to 30 characters. Thank you for your help. Please let me know if there's anything else you'd like me to do. :)

**Comment by coderjoe** [comment]
I'll be away for a few days so if there are any additional changes you need made to the PR I'll get back to you when I'm back. Thanks in advance for your help. :)

**Comment by jodastephen** [comment]
Thanks

**Pull request merged**
